/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.proyectointegrador.view;

import ucr.ac.cr.proyectointegrador.model.StudyPlan;

/**
 *
 * @author familiacr
 */
public class DataStudyPlanPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataStudyPlanPanel
     */
    public DataStudyPlanPanel() {
        initComponents();
    }

    public int getId() {
        return Integer.parseInt(this.txtId.getText());
    }

    public StudyPlan getStudyPlan() {
        return new StudyPlan(Integer.parseInt(this.txtId.getText()),
                this.txaDescription.getText(),
                Integer.parseInt(this.txtNumberCredits.getText()),
                this.txtApprovalDate.getText(),
                this.txtEffectiveDate.getText());
    }

    public void setStudyPlan(StudyPlan studyPlan) {
        this.txtId.setText(Integer.toString(studyPlan.getId()));
        this.txaDescription.setText(studyPlan.getDescription());
        this.txtNumberCredits.setText(Integer.toString(studyPlan.getNumberCredits()));
        this.txtApprovalDate.setText(studyPlan.getApproveDate());
        this.txtEffectiveDate.setText(studyPlan.getEffectiveDate());
    }

    public void clean() {
        this.txtId.setText("");
        this.txaDescription.setText("");
        this.txtNumberCredits.setText("");
        this.txtApprovalDate.setText("");
        this.txtEffectiveDate.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        txtNumberCredits = new javax.swing.JTextField();
        txtApprovalDate = new javax.swing.JFormattedTextField();
        txtEffectiveDate = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 540, 40));

        txaDescription.setColumns(20);
        txaDescription.setRows(5);
        jScrollPane1.setViewportView(txaDescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 540, 80));
        add(txtNumberCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 540, 40));

        try {
            txtApprovalDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(txtApprovalDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 540, 40));

        try {
            txtEffectiveDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(txtEffectiveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 530, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/planText_1.png"))); // NOI18N
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JFormattedTextField txtApprovalDate;
    private javax.swing.JFormattedTextField txtEffectiveDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumberCredits;
    // End of variables declaration//GEN-END:variables
}
