/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.proyectointegrador.view;

import java.awt.event.ActionListener;

/**
 *
 * @author familiacr
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void listen(ActionListener controller) {
        this.miExit.addActionListener(controller);
        this.miCredits.addActionListener(controller);
        this.miCourses.addActionListener(controller);
        this.miCareers.addActionListener(controller);
        this.miStudyPlans.addActionListener(controller);
        this.miReports.addActionListener(controller);
        this.miUsers.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCredits = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miCourses = new javax.swing.JMenuItem();
        miCareers = new javax.swing.JMenuItem();
        miStudyPlans = new javax.swing.JMenuItem();
        miUsers = new javax.swing.JMenuItem();
        miReports = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MAINGUI.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1310, 760));

        jMenuBar.setForeground(new java.awt.Color(102, 102, 255));
        jMenuBar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(153, 153, 255));
        jMenu1.setText("File");

        miCredits.setText("Credits");
        jMenu1.add(miCredits);

        miExit.setText("Exit");
        jMenu1.add(miExit);

        jMenuBar.add(jMenu1);

        jMenu2.setText("Modules");

        miCourses.setText(" Administration and maintenance of courses");
        miCourses.setActionCommand("Courses");
        jMenu2.add(miCourses);

        miCareers.setText("Administration and maintenance of careers");
        miCareers.setActionCommand("Careers");
        jMenu2.add(miCareers);

        miStudyPlans.setText("Administration and maintenance of study plans");
        miStudyPlans.setActionCommand("StudyPlans");
        jMenu2.add(miStudyPlans);

        miUsers.setText("Administration and maintenance o users");
        miUsers.setActionCommand("Users");
        jMenu2.add(miUsers);

        miReports.setText("Reports");
        jMenu2.add(miReports);

        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem miCareers;
    private javax.swing.JMenuItem miCourses;
    private javax.swing.JMenuItem miCredits;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miReports;
    private javax.swing.JMenuItem miStudyPlans;
    private javax.swing.JMenuItem miUsers;
    // End of variables declaration//GEN-END:variables
}
