/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.proyectointegrador.view;

import ucr.ac.cr.proyectointegrador.model.Career;

/**
 *
 * @author familiacr
 */
public class DataCareersPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataCareersPanel
     */
    public DataCareersPanel() {
        initComponents();
    }

    public int getCode() {
        return Integer.parseInt(this.txtCode.getText());
    }

    public Career getCourse() {
        return new Career(Integer.parseInt(this.txtCode.getText()),
                this.txtName.getText(),
                this.txaDescription.getSelectedText(),
                this.txaProfProfile.getText(),
                this.txaWorkingMarket.getText());
    }

    public void setCareer(Career career) {
        this.txtCode.setText(Integer.toString(career.getCode()));
        this.txtName.setText(career.getName());
        this.txaDescription.setText(career.getDescription());
        this.txaProfProfile.setText(career.getProfPerfil());
        this.txaWorkingMarket.setText(career.getWorkingMarket());
    }

    public void clean() {
        this.txtCode.setText("");
        this.txtName.setText("");
        this.txaDescription.setText("");
        this.txaProfProfile.setText("");
        this.txaWorkingMarket.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaProfProfile = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaWorkingMarket = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textCareers.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 590));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 630, 50));

        txtCode.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 630, 50));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 699, -1, -1));

        txaDescription.setColumns(20);
        txaDescription.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaDescription.setRows(5);
        jScrollPane1.setViewportView(txaDescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 630, 80));

        txaProfProfile.setColumns(20);
        txaProfProfile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaProfProfile.setRows(5);
        jScrollPane2.setViewportView(txaProfProfile);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 630, 74));

        txaWorkingMarket.setColumns(20);
        txaWorkingMarket.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaWorkingMarket.setRows(5);
        jScrollPane3.setViewportView(txaWorkingMarket);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 536, 630, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JTextArea txaProfProfile;
    private javax.swing.JTextArea txaWorkingMarket;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
