/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.proyectointegrador.view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author familiacr
 */
public class DataLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataLoginPanel
     */
    public DataLoginPanel() {
        initComponents();
    }

    public String getUsername() {
        return this.txtUsername.getText();
    }

    public String getPassword() {
        return this.jpPassword.getText();
    }

    public void clean() {
        this.txtUsername.setText("");
        this.jpPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUsername.setBorder(null);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 156, 450, 70));

        jpPassword.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jpPassword.setBorder(null);
        add(jpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 450, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelLogin.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 610));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
